### ISSUE TITLE
Upgraded to 1.1.1 and seeing random backlinks on many pages to unrelated pages

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#220] opened 2021-03-21 22:29 UTC
I've not manually created any links yet and seeing backlinks on many of my pages, also when editing if I don't delete the backlinks block then I will end up with multiple copies of it on save.

**Comment by Uzay-G** [comment] 2021-03-21 22:41
Oh crap it seems that I missed a few bugs. Thanks for reporting them! I'll try and fix it tomorrow :)

**Comment by Uzay-G** [comment] 2021-03-22 18:48
Could you maybe give me an example of the cases where you're getting random backlinks?

I can't replicate it.

As for the other problem, I'm on it :)

**Comment by Uzay-G** [comment] 2021-03-23 23:26
Alright the backlinks section being put inside the editor when it shouldn't be is fixed in the last commit, so once you give me more details for the other problem I'll fix that and deploy a new release :)

**Comment by BrianGilbert** [comment] 2021-03-28 00:37
@Uzay-G as far as I can tell it may be related to content containing spoecial charachter in the filename, particularly `/` my one peice of content containing that in the title is lkisted as a backlink on every other page.. or `|`, alternatively it may be related to imported webpages. 

One thing I do know is that I've not interlinked any of my created content within Archivy yet.

**Comment by BrianGilbert** [comment] 2021-03-28 02:28
In the first image you will see that it lists Reading Material as a backlink, in the second you can see that Reading Material contains no link to the first page. These pages are from different directory trees within Archivy too.

![TODO - Archivy 2021-03-28 13-26-14](https://user-images.githubusercontent.com/114017/112740505-5dcf5780-8fc9-11eb-8a4d-a7628e08be43.png)

![Reading Material - Archivy 2021-03-28 13-28-00](https://user-images.githubusercontent.com/114017/112740508-717abe00-8fc9-11eb-9de5-a1b59da04687.png)

**Comment by Uzay-G** [comment] 2021-03-28 09:28
You shouldn't be able to edit the backlinks directly like that, it's been fixed in the last release. That whole backlink section just appeared? :thinking:

**Comment by Uzay-G** [comment] 2021-03-28 09:29
I think I might know why, I'll try and fix it.

**Comment by BrianGilbert** [comment] 2021-03-29 00:49
> You shouldn't be able to edit the backlinks directly like that, it's been fixed in the last release. That whole backlink section just appeared? 🤔

Yeah I know you'd already fixed that, I just showed the edit view in case it gave you more infiormation 👍

**Comment by Uzay-G** [comment] 2021-03-29 16:53
Ok thanks. I've pinned down the cause for the other issue, and I'll try to have it fixed and released by thursday tops (a bit busy this week).

Sorry for that bug :sweat_smile:

**Comment by Uzay-G** [comment] 2021-04-04 17:24
@BrianGilbert could you test out the fixes I just pushed? You need to use the `source` image here: https://hub.docker.com/layers/uzayg/archivy/source/images/sha256-ba8caf1bd8b2f6524fa10b092dc9ad64b46afacfe6ef6a378ce22405f516b255?context=repo.

**Comment by BrianGilbert** [comment] 2021-04-06 00:29
@Uzay-G tested and seems to be working great, all the backlinks blocks I had have now disappered, and creating a manual backlink it displayed as expected.

**Comment by Uzay-G** [comment] 2021-04-06 21:03
Alright I pushed a new release `1.1.3`, thanks again :)

**Closed by Uzay-G** 2021-04-06 21:03 UTC
